version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

#    ports:
#      - "5432:5432"

  adminer:
    image: adminer
    profiles:
      - dbadmin
    restart: always
    ports:
      - 8081:8080


  order-delay:
#    image: ghcr.io/pa
    build:
      context: .

    ports:
      - "8080:8080"

    environment:
      DATABASES_DEFAULT_HOST: "postgres"
      DATABASES_DEFAULT_PORT: "5432"
      DATABASES_DEFAULT_USER: ${POSTGRES_USER:-postgres}
      DATABASES_DEFAULT_PWD: ${POSTGRES_PASSWORD:-postgres}
      DATABASES_DEFAULT_NAME: ${POSTGRES_DB:-postgres}
      RABBITMQCLIENT_CONNECTIONURL: "amqp://guest:guest@rabbitmq:5672"

    depends_on:
      - rabbitmq
      - postgres

    restart: on-failure


  migrate:
    image: migrate/migrate:v4.15.2
    profiles:
      - migration
    volumes:
      - ./internal/storage/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_DB:-postgres}:5432/${POSTGRES_DB:-postgres}?sslmode=disable",
      ]
    command: [ "up" ]
    depends_on:
      - postgres
    restart: on-failure