// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package entities

import (
	"context"
)

type Querier interface {
	AddDelayReports(ctx context.Context, db DBTX, arg AddDelayReportsParams) (int32, error)
	AssignOrderToAgent(ctx context.Context, db DBTX, arg AssignOrderToAgentParams) error
	GetAllDelaysInLastWeek(ctx context.Context, db DBTX) ([]GetAllDelaysInLastWeekRow, error)
	GetTripStatusByOrderId(ctx context.Context, db DBTX, id int32) (string, error)
}

var _ Querier = (*Queries)(nil)
